weblog/accounts/urls.py
from django.contrib.auth.views import LogoutView
from . import views
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('login/', views.signup_login, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

weblog/myblog/urls.py
from django.urls import path
from . import views
from . import views_api

app_name = 'myblog'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('simple_search/', views.simple_search, name='simple_search'),
    path('advanced_search/', views.advanced_search, name='advanced_search'),
    path('view_post/<int:post_id>/', views.view_post, name='view_post'),
    path('add_post/', views.add_post, name='add_post'),
    path('post_by_category/<int:category_id>/', views.post_by_category, name='post_by_category'),
    path('post_by_tag/<int:tag_id>/', views.post_by_tag, name='post_by_tag'),
    path('comment_like_dislike/<int:pk>/', views_api.LikeCommentLogList.as_view(), name='comment_like_dislike'),
    path('comment_like_dislike/', views_api.LikeCommentLogList.as_view(), name='comment_like_dislike'),
    path('post_like_dislike/<int:pk>/', views_api.LikePostLogList.as_view(), name='post_like_dislike'),
    path('post_like_dislike/', views_api.LikePostLogList.as_view(), name='post_like_dislike'),
]

weblog/weblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myblog/', include('myblog.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weblog/myblog/models.py
from django.db import models
from django.contrib.auth.models import User
from .validators import check_phone_number, check_tag


class UserExtraInfo(models.Model):
    class Meta:
        verbose_name = 'اطلاعات اضافي'

    phone = models.CharField('شماره تلفن', max_length=13, validators=[check_phone_number])
    image = models.ImageField('تصوير پروفايل', upload_to='avatars', null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='کاربر')

    def __str__(self):
        return f"كاربر {self.user}"


class Category(models.Model):
    class Meta:
        verbose_name = 'دسته‌بندي'
        verbose_name_plural = 'دسته‌بندي‌ها'

    name = models.CharField('نام', max_length=30, unique=True)
    parent = models.ForeignKey("Category", on_delete=models.CASCADE, verbose_name='سرشاخه', null=True, blank=True)

    def get_sub_groups(self):
        categories = Category.objects.filter(parent=self)
        return categories

    def __str__(self):
        return self.name


class Tag(models.Model):
    class Meta:
        verbose_name = 'برچسب'
        verbose_name_plural = 'برچسب‌ها'

    label = models.CharField(max_length=30, unique=True, validators=[check_tag])

    def count_used(self):
        return Post.objects.filter(tag__label=self.label).count()

    def __str__(self):
        return self.label


class Post(models.Model):
    class Meta:
        verbose_name = 'پست'
        verbose_name_plural = 'پست ها'
        permissions = [
            ("can_confirm_posts", "Can confirm all posts"),
            ("change_all_activation", "Can change all posts activations"),
            ("change_activation", "Can change just one activation"),
        ]

    title = models.CharField('عنوان', max_length=50)
    content = models.TextField('محتوا')
    image = models.ImageField('تصوير', upload_to='posts_img', null=True)
    tag = models.ManyToManyField(Tag, verbose_name='برچسب',
                                 help_text='برچسب ها با# آغاز مي‌شوند و فقط شامل حروف الفبا و _ مي‌شوند. '
                                           'برچسب‌ها را با فاصله از هم جدا كنيد', null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='دسته‌بندي')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='نويسنده')
    is_active = models.BooleanField('فعال', default=True)
    is_confirmed = models.BooleanField('مجاز', default=False)
    like = models.IntegerField('پسنديده', default=0)
    dislike = models.IntegerField('نپسنديده', default=0)
    pub_date = models.DateTimeField('تاريخ‌ انتشار', auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    class Meta:
        verbose_name = 'نظر'
        verbose_name_plural = 'نظرات'
        permissions = [
            ("can_confirm_comments", "Can confirm all comments"),
        ]

    content = models.TextField('متن نظر', max_length=400)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='پست')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='كاربر')
    is_confirmed = models.BooleanField('مجاز', default=False)
    like = models.IntegerField('پسنديده', default=0)
    dislike = models.IntegerField('نپسنديده', default=0)
    date_time = models.DateTimeField('تاريخ و زمان نظر', auto_now_add=True, blank=True)

    def __str__(self):
        return f'نظر كاربر {self.user}'


class LikeCommentLog(models.Model):
    class Meta:
        verbose_name = 'گزارش پسنديدن يا نپسنديدن نظر'
        verbose_name_plural = 'گزارشات پسنديدن يا نپسنديدن نظرات'
        unique_together = ['comment', 'user']

    comment = models.ForeignKey(Comment, on_delete=models.RESTRICT, verbose_name='نظر')
    user = models.ForeignKey(User, on_delete=models.RESTRICT, verbose_name='كاربر')
    # Like = True and Dislike = False
    like_or_dislike = models.BooleanField('پسنديدن يا نپسنديدن')

    def __str__(self):
        if self.like_or_dislike:
            return f'{self.user} پسنديده'
        else:
            return f'{self.user} نپسنديده'


class LikePostLog(models.Model):
    class Meta:
        verbose_name = 'گزارش پسنديدن يا نپسنديدن پست'
        verbose_name_plural = 'گزارشات پسنديدن يا نپسنديدن پست‌ها'

    post = models.ForeignKey(Post, on_delete=models.RESTRICT, verbose_name='پست')
    user = models.ForeignKey(User, on_delete=models.RESTRICT, verbose_name='كاربر')
    # Like = True and Dislike = False
    like_or_dislike = models.BooleanField('پسنديدن يا نپسنديدن')

    def __str__(self):
        if self.like_or_dislike:
            return f'{self.user} پسنديده'
        else:
            return f'{self.user} نپسنديده'

weblog/myblog/forms.py
from django import forms
from .models import *


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "category", "image"]
        tag = forms.SelectMultiple()


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]


def set_choices():
    authors = User.objects.filter(groups__name='نويسندگان')
    choices = list()
    for author in authors:
        choice = (author, str(author.get_full_name()))
        choices.append(choice)
    return choices


class PostSearchForm(forms.Form):
    title = forms.CharField(max_length=50, min_length=2, label="عنوان")
    content = forms.CharField(max_length=50, label="متن")
    author = forms.ChoiceField(choices=set_choices, label="نويسنده مطلب")
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple,
                                          label="برچسب")

weblog/myblog/views.py
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, HttpResponseRedirect, reverse, redirect
from django.contrib.postgres.search import SearchVector
from django.views import generic
from .forms import *
from .models import *
from .validators import check_tag_form


class Home(generic.ListView):
    template_name = 'myblog/index.html'
    context_object_name = 'posts_categories'

    def get_queryset(self):
        return [Category.objects.filter(parent=None),
                Post.objects.filter(is_active=True, is_confirmed=True).order_by('-pub_date'),
                Tag.objects.all()]


def view_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    comments = Comment.objects.filter(post=post, is_confirmed=True).order_by('date_time')

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            return HttpResponseRedirect(reverse('myblog:view_post', args=(post_id,)))
    else:
        comment_form = CommentForm()
    return render(request, 'myblog/view_post.html', {'post': post, 'comments': comments, 'comment_form': comment_form})


def post_by_category(request, category_id):
    posts = Post.objects.filter(Q(is_active=True, is_confirmed=True, category=category_id) |
                                Q(is_active=True, is_confirmed=True, category__parent=category_id))
    category_name = Category.objects.get(pk=category_id).name
    return render(request, 'myblog/by_category.html', {'posts': posts, 'name': category_name})


def post_by_tag(request, tag_id):
    posts = Post.objects.filter(tag=tag_id)
    tags = Tag.objects.all()
    return render(request, 'myblog/by_tag.html', {"posts": posts, "tags": tags})


def add_post(request):
    tags = Tag.objects.all()
    add_tags = list()
    if request.method == 'POST':
        post_form = PostForm(request.POST, request.FILES)
        print(post_form.errors)
        for tag in request.POST.getlist('tag'):
            if tag.isdigit():
                t = Tag.objects.get(pk=tag)
                add_tags.append(t)
            else:
                if check_tag_form(tag):
                    t = Tag.objects.create(label=tag)
                    add_tags.append(t)
                else:

                    return render(request, 'myblog/add_post.html', {"form": post_form, "tags": tags})

        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.author = request.user
            post.save()
            post.tag.add(*add_tags)
            post_form.save_m2m()
            return HttpResponseRedirect(reverse('myblog:home'))
    else:
        post_form = PostForm()

    return render(request, 'myblog/add_post.html', {"form": post_form, "tags": tags})


def simple_search(request):
    public_cat = Category.objects.filter(parent=None)
    if request.method == 'POST':
        key_word = request.POST.get('simple-search')
        posts = Post.objects.annotate(search=SearchVector('title', 'content', 'author__first_name',
                                                          'author__last_name')).filter(search=key_word)
        return render(request, 'myblog/search_results.html', {'public_categories': public_cat, 'posts': posts})
    else:
        return render(request, 'myblog/search_results.html', {'public_categories': public_cat, 'empty': True})


def advanced_search(request):
    public_cat = Category.objects.filter(parent=None)
    if request.method == 'POST':
        form = PostSearchForm(request.POST)
        if form.is_valid():
            posts = Post.objects.annotate(search=SearchVector('content')) \
                .filter(search=form.cleaned_data["content"], title=form.cleaned_data["title"],
                        tag__in=form.cleaned_data["tags"],
                        author=User.objects.get(username=form.cleaned_data['author']))
            return render(request, 'myblog/search_results.html', {'public_categories': public_cat, 'posts': posts})
        else:
            return HttpResponseRedirect(request.POST.get('next'))
    else:
        return render(request, 'myblog/search_results.html', {'public_categories': public_cat, 'empty': True})

weblog/myblog/templates/myblog/add_post.html
{% extends 'myblog/base.html' %}
{% block title %}افزودن پست{% endblock %}
{% load static %}
{% load bootstrap %}

{% block extra-link %}
<link rel="stylesheet" type="text/css" href="{% static 'myblog/css/add_post.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu">
<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block content %}

<form class="col-12 my-2 p-3 d-flex" action="{% url 'myblog:add_post' %}"
      enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <div class="col-6">
      <div class="form-row">
          <div class="form-group text-muted w-100 ml-4 mb-5">
            {{ form.category|bootstrap }}
              <div class="invalid-tooltip mr-5">
                  {{ form.category.errors }}
              </div>
          </div>
          <div class="form-group col-md-4 mt-2 mb-5">
              <input type="text" name="title" maxlength="50" class="form-control" placeholder="عنوان..." id="id_title" required>
              <div class="invalid-feedback">
                  {{ form.title.errors }}
              </div>
          </div>
          <div class="form-group col-md-8 mt-2 mb-4">
              <div class="container">
                <select class="js-select2 form-control" multiple="multiple" id="id_tag" name="tag">
                    {%  for tag in tags %}
                    <option value="{{ tag.id }}" data-badge="">{{ tag }}</option>
                    {% endfor %}
                </select>
                  <small class="text-warning">
                      <i class="fa fa-hand-o-left" aria-hidden="true"></i>
                      برچسب‌ها با # شروع شده و فقط شامل حروف الفبا و _ مي‌شوند.
                  </small>
              </div>
          </div>
          <div class="custom-file ml-3 mt-5">
            <input type="file" name="image" accept="image/*" value="dd" class="custom-file-input form-control" id="id_image">
            <label class="custom-file-label text-center" for="id_image">تصوير را انتخاب كنيد...</label>
            <div class="invalid-tooltip">
                  {{ form.image.errors }}
            </div>
          </div>
          <div class="col-12 text-center my-3 mt-5 pl-3 pr-0">
            <button type="submit" class="btn btn-primary w-100">افزودن &nbsp; پست</button>
          </div>
      </div>
    </div>
    <div class="col-6">
      <div class="form-row">
          <div class="form-group w-100 h-100">
            <label class="text-muted">متن پست:</label>
            <textarea name="content" cols="40" rows="10" class="form-control" id="id_content" required></textarea>
            <div class="invalid-feedback">
                {{ form.content.errors }}
            </div>
          </div>
      </div>
    </div>
</form>
<input type="hidden" name="next" value="{{ request.path }}">
{% endblock %}

{% block static %}
{{ block.super }}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
<script src="/static/myblog/js/add_post.js"></script>
{% endblock %}

weblog/myblog/templates/myblog/base.html
<!DOCTYPE html>
{% block links %}
{% load static %}
{% load bootstrap %}

<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.1/css/font-awesome.css"
          integrity="sha512-bf5lgyUrZOfPh94XyXFK4+2062lAMQFAfxUTVkOAHZ7R3XQ0tY+TUSkbqt8sjFsq0hVMKvGT/1P39c+vKwesTQ=="
          crossorigin="anonymous"/>
    <link rel="stylesheet" type="text/css" href="{% static 'myblog/css/base.css' %}">
    {% block extra-link %}{% endblock %}
</head>
{% endblock %}
<body dir="rtl" class="text-right">
{% block navbar %}
<div class="pos-f-t main-nav">
    <nav class="navbar navbar-dark bg-dark justify-content-between">
        <a href="{% url 'myblog:home' %}" class="text-decoration-none">
            <h1 class="text-muted">
                <i class="fa fa-bookmark-o" aria-hidden="true"></i>
                وبلاگ من
            </h1>
        </a>
        <div class="d-flex align-items-center">
            <form action="{% url 'myblog:simple_search' %}" dir="ltr" method="post">
                {% csrf_token %}
                <div class="bg-light rounded rounded-pill shadow-sm ml-3">
                    <div class="input-group d-flex align-items-center">
                        <div class="input-group-prepend">
                            <button id="button-addon2" type="submit" class="btn btn-linktext text-primary">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                        <input type="search" placeholder="جستجو" name="simple-search"
                               class="form-control border-0 m-0 mr-3 bg-light text-right"
                               data-toggle="tooltip" data-placement="bottom" style="height: 1em;"
                               title="جستجوي همزمان در عنوان ، متن و نويسنده مطلب" autocomplete="off">
                    </div>
                </div>
            </form>
            <button class="btn btn-outline-light h-50 py-0 px-2 mr-2" type="button" data-toggle="collapse"
                    data-target="#navbarToggleExternalContent" id="main" onclick="openNav()">
                <span style="font-size: 24px;">&#9776;</span>
            </button>
        </div>
    </nav>
</div>

<div id="mySidenav" class="sidenav test-center">
    <div class="col-12 text-center mb-4">
        {% if not request.user.is_authenticated or request.user.userextrainfo.image == null %}
        <img src="http://s3.amazonaws.com/37assets/svn/765-default-avatar.png"
             class="rounded-circle" width="130" alt="Default Avatar"/>
        {% else %}
        <img src="{{ request.user.userextrainfo.image.url }}" style="background-size: cover;"
             class="rounded-circle" width="130" height="130" alt="Default Avatar"/>
        {% endif %}
    </div>
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">
        <i class="fa fa-times" aria-hidden="true"></i>
    </a>
    {% if not request.user.is_authenticated %}
    <input class="form-control mt-0 mb-3 text-center" value="شما وارد حساب كاربري خود نشده‌ايد." readonly>
    {% else %}
    <div class="bg-dark py-1 my-2" style="opacity: 0.5;">
        <p class="text-center font-weight-bolder text-light shadow-lx">{{ request.user.get_full_name }}
        عزيز خوش آمديد
        </p>
    </div>
    {% endif %}
    <div class="col-7 mx-auto text-center">
        {% if not request.user.is_authenticated %}
        <a href="{% url 'myblog:home' %}" class="btn-secondary px-2">خانه</a>
        <a href="{% url 'accounts:login' %}" class="btn-secondary mt-2 px-2">ورود/ ثبت‌نام</a>
        <button class="btn-secondary mt-2 px-2 border-0" data-toggle="modal" data-target="#append"
                onclick="closeNav()" id="sch">
            جستجوي پيشرفته
        </button>
        <a href="#" class="btn-secondary mt-2 px-2">درباره ما</a>
        {% endif %}
        {% if request.user.is_authenticated %}
        <a href="{% url 'myblog:home' %}" class="btn-secondary px-2">خانه</a>
        <button class="btn-secondary mt-2 px-2 border-0" data-toggle="modal" data-target="#append"
                onclick="closeNav()" id="sch">
            جستجوي&nbsp; پيشرفته
        </button>
        <a href="#" class="btn-secondary mt-2 px-2">درباره ما</a>
        <a href="{% url 'accounts:logout' %}" class="btn-secondary mt-2 px-2">خروج</a>
        {% endif %}
    </div>

</div>

<div class="modal fade" id="append" tabindex="-3" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header p-1">
              <span class="mb-2">
                <h5 class="modal-title mt-3 mb-0">جستجوي پيشرفته</h5>
                <small>
                    <i class="fa fa-exclamation-circle text-danger" aria-hidden="true"></i>
                    توجه فرماييد كه كلمات عيناً جستوجو مي‌شوند!
                </small>
              </span>
                <button type="button" class="btn btn-outline-secondary m-0 p-1 border-0" data-dismiss="modal">
                    <i class="fa fa-times-circle" aria-hidden="true"></i>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'myblog:advanced_search' %}" enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col">
                            <input type="text" class="form-control" placeholder="{{ search_form.title.label }}"
                                   id="id_title" name="title" maxlength="50" minlength="2" required>
                        </div>
                        <div class="col">
                            <input type="text" class="form-control" placeholder="{{ search_form.content.label }}"
                                   id="id_content" name="content" maxlength="50" required>
                        </div>
                    </div>
                    <div class="form-col mt-2">
                        {{ search_form.author|bootstrap }}
                    </div>
                    <label>برچسب ها</label>
                    <div class="form-control" id="selection">
                        {{ search_form.tags }}
                    </div>
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <div class="col-12 text-center">
                        <button type="submit" class="btn btn-outline-primary mt-3">جستجوي پست</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="main-container m-0 p-0"></div>
{% endblock %}

{% block static %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="/static/myblog/js/base.js"></script>
{% endblock %}
</body>
</html>

weblog/myblog/templates/myblog/view_post.html
{% extends 'myblog/base.html' %}
{% block title %}مشاهده پست{% endblock %}
{% load static %}
{% load bootstrap %}

{% block extra-link %}
<link rel="stylesheet" type="text/css" href="{% static 'myblog/css/view_post.css' %}">
{% endblock %}

{% block content %}
<div class="col-12 py-4 px-5 d-flex justify-content-between">
    <div class="col-12 rounded bg-light p-0">
        <div class="row m-0 p-2 d-flex justify-content-between">
            <div class="col">
                <h2 class="font-weight-bold mb-5">
                    <i class="fa fa-check" aria-hidden="true"></i>
                    {{ post.title }}
                </h2>
                <div class="card border-dark mb-3 " style="max-width: 28rem">
                    <div class="card-header">اطلاعات پست</div>
                    <div class="card-body text-dark">
                        <div class="col d-flex p-0">
                            <img src="{{ post.author.userextrainfo.image.url }}" class="img-thumbnail rounded"
                                 width="70">
                            <div class="col pt-2">
                                <h6 class="mb-4">
                                    <table>
                                        <tr>
                                            <td class="font-weight-bold">نويسنده:</td>
                                            <td>&nbsp;</td>
                                            <td class="text-muted">{{ post.author.get_full_name }}</td>
                                        </tr>
                                    </table>
                                </h6>
                                <table>
                                    <tr>
                                        <td class="font-weight-bold">دسته‌بندي:</td>
                                        <td>&nbsp;</td>
                                        <td>
                                            <a href="{% url 'myblog:post_by_category' post.category.id %}"
                                               class="text-decoration-none">
                                                {{ post.category }}
                                            </a>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <p class="d-block font-weight-bold m-0">برچسب‌ها:</p>
                        {% for tag in post.tag.all %}
                        <a href="{% url 'myblog:post_by_tag' tag.id %}" class="btn-sm btn-dark m-1">
                            &nbsp;{{ tag }}
                        </a>
                        {% endfor %}
                    </div>
                    <div class="card-footer p-0 d-flex justify-content-between">
                        <small class="text-muted mr-2">آخرين ويرايش:</small>
                        <small class="text-muted ml-2" id="pub-date">{{ post.pub_date }}</small>
                    </div>
                </div>
            </div>
            <img src="{{ post.image.url }}" class="rounded" width="500">
        </div>
        <p class="my-3 mb-1 mx-5">{{ post.content }}</p>
        {% if request.user.is_authenticated %}
        <div class="btn-group-vertical btn-group-toggle post-action" data-toggle="buttons" dir="ltr" style="float: left;margin-top: -5em;">
            <button class="btn btn-dark rounded-circle p-2 like-post" id="{{ post.id }}-lp">
                <i class="fa fa-thumbs-up fa-lg" aria-hidden="true"></i>
            </button>
            <span class="badge badge-pill badge-info">{{ post.like}}</span>
            <button class="btn btn-dark rounded-circle p-2 dislike-post" id="{{ post.id }}-dp">
                <i class="fa fa-thumbs-down fa-lg" aria-hidden="true"></i>
            </button>
            <span class="badge badge-pill badge-info">{{ post.dislike}}</span>
        </div>
        {% endif %}
    </div>
</div>

{% if request.user.is_authenticated %}
<div class="col-11 bg-dark mx-auto mb-4 mt-2 py-2 px-5 shadow" style="border-radius: 130px;">
    <form enctype="multipart/form-data" class="d-flex flex-column" action="{% url 'myblog:view_post' post.id %}"
          method="post">
        {% csrf_token %}
        <div class="col d-flex justify-content-start">
            <img src="{{ request.user.userextrainfo.image.url }}" class="rounded-circle ml-3 mt-auto"
                 width="70" height="70">
            <div>
                <p class="text-light bd-highlight">{{ request.user.get_full_name }}:</p>
                <textarea name="content" cols="40" rows="2" maxlength="400" class="form-control d-inline"
                          id="id_content" placeholder="شما هم نظر بگذاريد..." required style="width: 52em"></textarea>
            </div>
        </div>
        <input type="submit" value="ثبت نظر" class="btn btn-outline-light w-25 mx-auto my-2">
    </form>
</div>
{% endif %}

<div class="col-11 mx-auto mb-3 rounded shadow comments">
    {% for comment in comments %}
    <div class="p-3 d-flex align-items-center justify-content-center">
        <img src="{{ comment.user.userextrainfo.image.url }}" class="rounded-circle ml-3"
             width="70" height="70">
        <div class="col-10">
            <p class="text-primary mb-0">{{ comment.user.get_full_name }}:</p>
            <div class="col-11 p-3 bg-dark h-75 d-flex align-items-center justify-content-between rounded">
                <p class="text-light my-auto">{{ comment.content }}</p>
                {% if request.user.is_authenticated %}
                <div class="btn-group btn-group-toggle" data-toggle="buttons" dir="ltr">
                    <button class="btn bg-light rounded-circle p-2 like" id="{{ comment.id }}-l">
                        <i class="fa fa-thumbs-up fa-lg" aria-hidden="true"></i>
                    </button>
                    <span class="badge badge-pill badge-danger">{{ comment.like}}</span>
                    <button class="btn bg-light rounded-circle p-2 dislike" id="{{ comment.id }}-d">
                        <i class="fa fa-thumbs-down fa-lg" aria-hidden="true"></i>
                    </button>
                    <span class="badge badge-pill badge-danger">{{ comment.dislike}}</span>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    <hr class="mx-5 bg-secondary">
    {% endfor %}
</div>
<input type="hidden" name="next" value="{{ request.path }}">

<script>
var now = new Date({{ post.pub_date.year }}, {{ post.pub_date.month }}, {{ post.pub_date.day }},
{{ post.pub_date.hour }}, {{ post.pub_date.minute }}, {{ post.pub_date.second }})
</script>

{% endblock %}

{% block static %}
{{ block.super }}
<script src="https://gist.github.com/unicornist/0e37b3691551c42c716e96c125b99df7.js"></script>
<script src="/static/myblog/js/view_post.js"></script>
{% endblock %}